# 데이터사이언스 (0010085001)

## Exercise 3: Libraries for Data Science (NumPy)

In this excercise, we will cover NumPy library

### Array creation routines
* Ones and zeros

In [1]:
import numpy as np

In [7]:
# Create an 2-by-2 array of all zeros 
a = 
print(a)

[[0. 0.]
 [0. 0.]]
float64


In [8]:
# Create an 2-by-2 array of all ones 
a = 
print(a)

[[1 1]
 [1 1]]
int16


In [11]:
# Create an 2-by-2 array with random numbers
a = 
print(a)

[[0.73480718 0.27003699]
 [0.6591247  0.78326482]]
[[0.30839622 0.58159871]
 [0.56831323 0.53160267]]


In [12]:
# Create an 1-by-6 array with elements 1 to 6
a = 
print(a)

[1 2 3 4 5 6]


In [14]:
# Create a two rows array with elements 1 to 6
b = 
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
# Print shape of the array
print(b.shape)

(2, 3)


In [ ]:
#  Create an array of zeros with the same shape and type as b
c = 
print(c)

In [ ]:
# Create an array of ones with the same shape and type as b
d = 
print(d)

In [ ]:
# Create a new array of 2*5 uints, filled with 6.
# Use np.full() and np.ones()
a = 
print(a)

b = 
print(b)

### Array from existing data

In [ ]:
# Create an array of [1, 2, 3]
a = 
print(a)

In [ ]:
# Let x = [1, 2]. Convert it into an array (asarray)
x = 
x = 
print(x)

In [ ]:
# Let x = np.array([[1, 2], [3, 4]]). Convert it into a matrix (asmatrix)
x = 
x = 
print(x)

In [ ]:
# Let x = [1, 2]. Convert it into an array of float (asfarray)
x = 
x = 
print(x)
print(type(x[0]))

y = 
print(y)
print(type(y[0]))

In [ ]:
# Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30 (asscalar)
x = 
x = 
print(x)

In [ ]:
# Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x
x = 
y = 
print(id(x), x)
print(id(y), y)

### Array indexing
Since arrays may be multidimensional, you must specify a slice for each dimension of the array

In [ ]:
# Create an 3-by-4 array with elements 1 to 12 (reshape)
a = 
print(a)

In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2
b = 
print(b)

In [ ]:
# From an array, print all rows which sum up to less or equal two
x = 
rowsum = 
print(rowsum)

### Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

In [ ]:
#############################################################
# General Usage
#############################################################
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise product of x and y
z = 
print(z)

In [ ]:
# Matrix product of x and y
z = 
print(z)

In [ ]:
# Compute sum of all elements in x
z = 
print(z)

In [ ]:
# Compute sum of each column in x;
z = 
print(z)

In [ ]:
# Compute sum of each row in x
z = 
print(z)

In [ ]:
#############################################################
# Broadcasting
#############################################################

a = np.array([[0.0, 0.0, 0.0,],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])

print(a+b)

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) 

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

In [ ]:
# Add the vector v to each row of the matrix x with stacking v multiple times (tile)
vv = 
y = x + vv
print(y)

In [ ]:
# Add the vector v to each row of the matrix x with broadcasting
y = 
print(y)

In [ ]:
# Multiply matrix x by a constant 2:
z = 
print(z)

### Numpy Array as Data

* Data type: scalar, vector, matrix, tensor, and so on


In [ ]:
# Feature vector example 1

from sklearn.datasets import load_iris

iris = load_iris() 
print(iris.data[0, :])

In [ ]:
# Feature vector example 2
import matplotlib.pyplot as plt

from sklearn.datasets import load_digits 
digits = load_digits()  # 데이터 로드
samples = [0, 10, 20, 30, 1, 11, 21, 31]  # 선택된 이미지 번호
d = []
for i in range(8):
    d.append(digits.images[samples[i]])

plt.figure(figsize=(8, 2))
for i in range(8):
    plt.subplot(1, 8, i + 1)
    plt.imshow(d[i], interpolation='nearest', cmap=plt.cm.bone_r)
    plt.grid(False); plt.xticks([]); plt.yticks([])
    plt.title("image {}".format(i + 1))
plt.suptitle("숫자 0과 1 이미지")
plt.tight_layout()
plt.show()

### Image processing with Python, NumPy

In [ ]:
from PIL import Image # Python Imaging Library
import numpy as np
import scipy.misc
import cv2

# How to read an image file as ndarray
image_url = "https://github.com/nkmk/python-snippets/blob/1dd9bd0b89a4465af229cbbfc2a1f8e3cb26d78c/notebook/data/src/lena.jpg"

# Download image and move it to the file (see left categories)
im = 

# Convert Image to numpy.ndarray
im = 

print(im.shape)
print(im.dtype)
print(im.shape)

In [ ]:
# Convert image to grayscale
im_gray = 
print(im_gray.shape)

In [ ]:
# Change the value of the element (pixel)
print(im.flags.writeable)

print(im[0, 0, 0])

im[0, 0, 0] = 0

print(im[0, 0, 0])

In [ ]:
# Generation of single color image and concatenation
image_url = "https://github.com/nkmk/python-snippets/blob/1dd9bd0b89a4465af229cbbfc2a1f8e3cb26d78c/notebook/data/src/lena_square.png?raw=true"

im = 
im = 

# Make green and blue channel values to zero
im_R = im.copy()
im_R

# Make red and blue channel values to zero
im_G = im.copy()
im_G

# Make red and green channel values to zero
im_B = im.copy()
im_B

# Concatenate each images along the axis 1
im_RGB = 
# im_RGB = np.hstack((im_R, im_G, im_B))
# im_RGB = np.c_['1', im_R, im_G, im_B]

# Save image
pil_img = Image.fromarray(im_RGB)
pil_img.save('./lena_numpy_split_color.jpg')


In [ ]:
# Negative-positive inversion (invert pixel value)
im = np.array(Image.open('./lena_square.jpg').resize((256, 256)))

im_i = 

Image.fromarray(im_i).save('./lena_numpy_inverse.jpg')

In [ ]:
# Color reduction
im = np.array(Image.open('./lena_square.jpg').resize((256, 256)))

im_32 = im // 32 * 32
im_128 = im // 128 * 128

im_dec = 

Image.fromarray(im_dec).save('./lena_numpy_dec_color.jpg')

In [ ]:
# Trimming with slice
m = np.array(Image.open('./lena_square.jpg'))
print(im.shape)

# Slice image with arbitrary scale
im_trim1 = im[]
print(im_trim1.shape)

Image.fromarray(im_trim1).save('./lena_numpy_trim.jpg')